name: pti-tools-build-and-test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - sdk/**
      - .github/**
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - sdk/**
      - .github/**

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  pti-tools-build-and-test:
    name: Test pti tools Ubuntu-22-04

    if: vars.PTI_RUN_TESTS == 1

    runs-on: [self-hosted, Linux, pti]

    strategy:
      matrix:
        include:
          - container: ${{ vars.PTI_DOCKER_IMAGE_2024_1_1 }}

    container: 
      image: ${{ matrix.container }}
      options: --device=/dev/dri --cap-add CAP_PERFMON

    steps:
      - name: Clean-up
        run:  rm -rf *

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build-unitrace
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s unitrace-build

      - name: Test-unitrace
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s unitrace-test

      - name: Build-and-test-onetrace
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s onetrace

      - name: Build-and-test-oneprof
        run: |
          source /opt/intel/oneapi/setvars.sh
          #
          # Must with more than one GPU because of
          # an random failures as documented in PTI-75
          #
          if [ $(sycl-ls|grep 'ext_oneapi_level_zero:gpu:' -c) -gt 1 ]; then
            exit 0
          fi
          python ./tests/run.py -s oneprof

      - name: Build-and-test-sysmon
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s sysmon

      - name: Build-and-test-cl_gpu_metrics
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s cl_gpu_metrics

      - name: Build-and-test-instcount
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s instcount

      - name: Build-and-test-ze_debug_info
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s ze_debug_info

      - name: Build-and-test-cl_debug_info
        run: |
          source /opt/intel/oneapi/setvars.sh
          python ./tests/run.py -s cl_debug_info

  pti-tools-build-and-test-windows:

    name: Test unitrace on Windows

    if: vars.PTI_RUN_TESTS == 1

    runs-on: [self-hosted, Windows, pti]

    defaults:
      run:
        shell: cmd

    steps:
      - name: Clean-up
        run: |
          del /S /Q /F *

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build-unitrace
        run: |
          @echo off
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          python ./tests/run.py -s unitrace-build

      - name: Test-unitrace
        run: |
          @echo off
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          python ./tests/run.py -s unitrace-test
